# Generated by Django 5.2.1 on 2025-08-22 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Enter your WhatsApp number with country code (e.g., +923001234567)', max_length=20, null=True),
        ),
    ]
